### ISSUE TITLE
Bug: When pulling from instances *and* an external list source, breaks the Min strategy

### ISSUE THREAD

**Issue by sgrigson** [eigenmagic/fediblockhole#22]
To replicate:

Pull from a list of servers. Using a `min` strategy, make sure one of the sites is Silenced.

Then pull from an external file source (I tested the rapidblock json file, but CSVs seem to be the same issue.) It appears that the `min` strategy does not work properly when you pull from a file, only when choosing between instances.

If you have a 'Suspend' value in an external file, while also pulling from instances where 'Silence' exists, you'll still end up with Suspend in the final merge file/output. This appears to be because CSV and other file types are automatically applying a "Max" strategy behind the scenes.

**Comment by sgrigson** [comment]
I think I figured out the issue.

It's the `mergeplan` of 'min' in the config file being ignored. If I add the mergeplan to the command line it works properly.

**Comment by jpwarren** [comment]
Weird! Thanks for looking at that in more detail. I was able to find the problem faster with the extra information.

I've fixed it and merged in PR #23
