### ISSUE TITLE
Python 3.10 requirement blocks installation on common distros

### ISSUE THREAD

**Issue by JamesHarrison** [eigenmagic/fediblockhole#41]
Hi,

Python 3.10 or greater is defined in the pyproject file as a requirement. However, I don't think from a quick review any 3.10 specific features are required, and some distros don't ship 3.10 (e.g. Debian stable is 3.9.2 at present). This means attempting to install yields an error. 

I've configured and tested with 3.9.2 and it seems to work just fine, so I think this is perhaps an overzealous requirement - could it be dropped?

Thanks for your work - it's a great tool to have for smaller instance operators wanting to keep Mastodon clean!

**Comment by jpwarren** [comment]
It's overly conservative, yeah. I'll drop it to 3.6 which is around Ubuntu bionic (18.04LTS). It might be fine further back than that, but n-2 LTS distros seems like a large enough set of supported versions.

I haven't done an audit of compatibility for different Python versions but if someone uses it on a really old version and hits a bug, we can adjust the version number again.

**Comment by jpwarren** [comment]
Fixed in df3c16f
