### ISSUE TITLE
Support Native 4.1 Mastodon Export Format

### ISSUE THREAD

**Issue by sgrigson** [eigenmagic/fediblockhole#43]
It's worth mentioning that the files produced by Fediblockhole and the files produced by the export process are *almost* identical.

Fediblockhole:

`domain, severity, reject_media, reject_reports, public_comment, obfuscate`

Mastodon/Glitch, etc:

`#domain, #severity, #reject_media, #reject_reports, #public_comment, #obfuscate`

It would be good if Fediblockhole could read and support either format.

**Comment by jpwarren** [comment]
It would be good if people didn't use the character commonly used everywhere else to specify "this is a comment" as the first character in their field names in a CSV.

Whyyyyyy?

**Comment by sgrigson** [comment]
Right?? It's the worst thing ever.

When you import the fediblockhole files I think it has to be imported in that order I listed above if you don't have proper column headers, and you have to uncheck the first row every time because it thinks the domain to block is "domain".

So it would arguably be nice to both accept input (and optionally output) of the hash-prefix header just for full interoperability.
