### ISSUE TITLE
Offer a method for keeping the token out of configuration

### ISSUE THREAD

**Issue by offbyone** [eigenmagic/fediblockhole#61]
When referring to the `token` parameter, it would be really nice if we could reference it from either keyring or an environment variable, rather than needing to keep it in configuration. I want to commit these configs to git... and I think that maybe putting an admin-scoped API token in my git history is a bad idea :D

**Comment by jpwarren** [comment]
Good idea! I'll take a look at the PR.

**Comment by jpwarren** [comment]
I like the idea of using environment variables so we can have ephemeral secrets. That is definitely a thing we want.

Before we commit to this particular implementation of the idea, what other ways could we use to achieve it, and is this kind of special syntax/marker method the best one? Or the least bad? Can we avoid using special markers/syntax completely?

I'm wary of going down a particular path before we look a little bit ahead and see if we're going to hurt ourselves later on. What alternatives were looked at before settling on this method? Is this something we will want to make more general later so it can apply to more things?

I don't want to overthink it and stall all progress or discourage improvements like this. Just want to make sure I understand the implications and make future me/us pleased with what we did instead of cursing our naive enthusiasm.

What do you reckon?

**Comment by offbyone** [comment]
I considered a more comprehensive template idea -- jinja2 values with the environment available to the context, for example -- or just conventional `$<VAR>` syntax. I went with this one because it was both unambiguous and simple to implement and reason about. Bare `$VAR` syntax was too ambiguous, and jinja2 support leads to needing extension support, which is a whole-ass mess too. 

Keyring support was another direction I considered, but in those cases it almost needs a whole other set of keys in the dict to get the values, and keyring support is uneven on Linux in my experience, especially headless. 

For the syntax,  ¯\_(ツ)_/¯, I'm not attached to this, but I'm pretty okay with it. I think if it were my project I'd be cautious about overgeneralizing; we're not looking at a service configuration system here, we're looking at a script config file. The only reason to have an indirection here is so that the file can be safely committed to source control. Anything that can serve that need is good by me.

**Comment by jpwarren** [comment]
I've thought of a couple of alternate ways to implement this idea:

1. Add a new key to the config dictionary for `blocklist_instance_sources` and `blocklist_instance_destinations` such as `token_env_var` that defines the name of the env var to look for. Then we don't have to parse a key:value string nested inside what is already a key:value structure.
2. Use the domain name to build the env var name via string substitution. e.g. the domain `eigenmagic.net` would have a token in the environment as `$EIGENMAGIC_NET_TOKEN` or similar.

Or why not both, added to existing functionality?

That would give us the following algorithm:

1. If the `token` key is provided in the config dictionary, use this specific token from the config file. Same functionality as now. If permissions on the config file are limited appropriately, this is reasonably secure and has fewer moving parts.
2. If a new `token_env_var` key is provided, use the provided string value as the name of the environment variable that contains the token. e.g.: `token_env_var = 'EIGENMAGIC_BEARER_TOKEN'`. The code would then fetch the token from this environment variable. Consider: do we force the env name to UPPERCASE or leave it as specified? I am inclined to let people use lowercase or mixed case if they want to, but UPPERCASE would be encouraged.
3. If no `token_env_var` key is provided, and no `token` was provided, look for a token in the environment variable named `<domain_with_underscores>_TOKEN` where `<domain_with_underscores>` is the `domain` provided with dots converted to underscores and `_TOKEN` appended. `domain = eigenmagic.net` would result in an environment variable named `EIGENMAGIC_NET_TOKEN` and that's what we would look for in the environment for the token.

This would provide a sensible default with override options and remain backwards compatible with existing deployments.

What do you think?

**Comment by offbyone** [comment]
I gave it a stab.

I'm not sure I like it because it's a pain to describe, which always feels "off" to me, but I agree it's less ambiguous. Have a look at the latest rev of the PR

**Comment by offbyone** [comment]
I'd suggest that you look at #64 before this, and I can rebase onto it; that adds automatic testing to the package :D
