### ISSUE TITLE
Run CI on pull requests

### ISSUE THREAD

**Issue by offbyone** [eigenmagic/fediblockhole#65]
Adding CI on pull requests that runs the tests for fediblockhole on all pull requests and commits to `main` provides the maintainer evidence that a PR hasn't broken any functionality that is covered by the tests.

While there are a lot of options for CI, I generally recommend a minimal set:

- does the code package up for distribution on PyPi?
- do tests run successfully?
- check coverage levels

I already sent in a PR for it: #64

**Comment by jpwarren** [comment]
Can you please update the issue to explain why it is an issue and should be addressed?

It might be obvious to you, but it might not be obvious to others. I believe I understand why this is a good idea, but I'm not 100% sure I know it's the same as what _you_ believe.

It'll also help others who come after us, especially if they are new at this. Or just future me who will have forgotten all about this and will have to retrieve the memories from deep storage. Let's help them understand what happened and why.

Doesn't need to be War and Peace, but let's not be inscrutable Old Ones either.

**Comment by jpwarren** [comment]
Confirmed that CI now runs on PRs with #69.

Merge of PR #64 did what it was supposed to do.
